
package com.tahaakocer.externalapiservice.soap;
//------------------------------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 9.3.3.2
//
// Created by Quasar Development 
//
// This class has been generated for test purposes only and cannot be used in any commercial project.
// To use it in commercial project, you need to generate this class again with Premium account.
// Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
//
// Licence: C55D9165152C7CEFF67AC92556F3954265D1E3E8B03A5844FDDFFB1D89954928B8DFE17E0F5C9E109058269407DC935D4D14154DF01523D1C70BACAAE57FA874
//------------------------------------------------------------------------
import java.net.URL;
import java.io.*;
import java.net.HttpURLConnection;
import java.util.HashMap;
import java.util.Map;
import java.util.List;

public interface NSNConnectionProvider
{
    NSNResponseData sendRequest(String url,String requestBody,HashMap< String,String> httpHeaders, NSNRequestResultHandler handler,String contentType) throws java.lang.Exception;
}

class NSNHttpConnectionProvider implements NSNConnectionProvider{

    public void prepareRequest(HttpURLConnection url,String requestBody, NSNRequestResultHandler handler,String contentType ) throws java.lang.Exception {
        OutputStreamWriter wr = new OutputStreamWriter(url.getOutputStream());
        wr.write(requestBody);
        wr.flush();
    }

    @Override
    public NSNResponseData sendRequest(String url,String requestBody, HashMap< String, String> httpHeaders,NSNRequestResultHandler handler,String contentType ) throws java.lang.Exception
    {
        URL urlObject=new URL(url);
        HttpURLConnection connection=(HttpURLConnection)urlObject.openConnection();
        connection.setDoOutput(true);
        connection.setRequestMethod("POST");
        for(Map.Entry<String, String> entry : httpHeaders.entrySet())
        {
            connection.setRequestProperty(entry.getKey(),entry.getValue());
        }
        connection.setRequestProperty("user-agent","https://easyWSDL.com Generator 9.3.3.2");
        prepareRequest(connection,requestBody,handler, contentType );


        NSNResponseData response=new NSNResponseData();
        for(Map.Entry<String, List<String>> entry : connection.getHeaderFields().entrySet())
        {
            if(entry.getKey()!=null)
            {
                String values = "";
                for (String value : entry.getValue()) {
                    values = values + value;
                }
                response.getHeaders().put(entry.getKey(),values);
            }
        }
        
        try(InputStream dataStream = getResponseStream(connection,response,handler))
        {
            response.setBody(NSNHelper.streamToString(dataStream));
        }
        
        return response;
    }

    protected InputStream getResponseStream(
        HttpURLConnection url,
        NSNResponseData response,
        NSNRequestResultHandler handler
    ) throws java.lang.Exception
    {
        try{
            return url.getInputStream();
        }
        catch (IOException ex)
        {
            return url.getErrorStream();
        }
    }
}