
package com.tahaakocer.externalapiservice.soap;
//------------------------------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 9.3.3.2
//
// Created by Quasar Development 
//
// This class has been generated for test purposes only and cannot be used in any commercial project.
// To use it in commercial project, you need to generate this class again with Premium account.
// Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
//
// Licence: C55D9165152C7CEFF67AC92556F3954265D1E3E8B03A5844FDDFFB1D89954928B8DFE17E0F5C9E109058269407DC935D4D14154DF01523D1C70BACAAE57FA874
//------------------------------------------------------------------------
import java.util.HashMap;
import java.util.Map;
import java.util.List;



public class NSNResponseData
{
    private HashMap< String,String> headers = new HashMap< String,String>();
    private String body;

    public HashMap< String,String> getHeaders()
    {
        return headers;
    }
    
    public String getBody()
    {
        return body;
    }

    public void setBody(String body)
    {
        this.body=body;
    }
}